(() => {
    const state = { view: 'dashboard', clusters: [], history: [], stats: null, loading: false };
    const $ = (selector) => document.querySelector(selector);
    const $$ = (selector) => [...document.querySelectorAll(selector)];
    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
    const arrayFrom = (payload, keys) => { if (Array.isArray(payload)) return payload; for (const key of keys) if (Array.isArray(payload?.[key])) return payload[key]; return []; };

    function toast(message, error = false) {
        const item = document.createElement('div'); item.className = `toast${error ? ' error' : ''}`; item.textContent = message; $('#toast-region').append(item); setTimeout(() => item.remove(), 3500);
    }
    function setConnection(status, detail) { $('#connection-dot').className = `status-dot ${status || ''}`; $('#connection-label').textContent = status === 'online' ? 'Backend đang online' : status === 'error' ? 'Backend không phản hồi' : 'Chưa kết nối backend'; $('#connection-detail').textContent = detail; }
    function emptyState(title, detail, icon = 'fa-plug') { return `<div class="empty-state"><div><i class="fa-solid ${icon}"></i><strong>${escapeHtml(title)}</strong><p>${escapeHtml(detail)}</p></div></div>`; }
    function setLoading(isLoading) { state.loading = isLoading; $('#refresh-button').disabled = isLoading; $('#queue-refresh').disabled = isLoading; $('#refresh-button i').classList.toggle('fa-spin', isLoading); }
    function normalizeCluster(cluster) { return { ...cluster, id: cluster.id ?? cluster.cluster_id ?? cluster.turn_id, question: cluster.question ?? cluster.main_question ?? cluster.representative_msg?.text ?? cluster.text ?? '', count: Number(cluster.count ?? cluster.message_count ?? 0), score: Number(cluster.final_score ?? cluster.total_score ?? cluster.score ?? 0), type: cluster.type ?? cluster.status ?? 'academic', reason: cluster.reason ?? cluster.explanation ?? '', messages: cluster.messages ?? cluster.raw_messages ?? [] }; }
    function readMetric(keys) { for (const key of keys) if (state.stats?.[key] !== undefined) return state.stats[key]; return '--'; }

    async function loadData() {
        if (!QARadarApi.isConfigured()) { setConnection('', 'Cấu hình API để bắt đầu'); renderAll(); return; }
        setLoading(true); setConnection('', 'Đang tải dữ liệu...');
        try {
            const [stats, clusters, history] = await Promise.all([QARadarApi.getStats(), QARadarApi.getClusters(), QARadarApi.getHistory()]);
            state.stats = stats || {}; state.clusters = arrayFrom(clusters, ['clusters', 'items', 'data']).map(normalizeCluster); state.history = arrayFrom(history, ['history', 'items', 'data']);
            setConnection('online', `${state.clusters.length} cụm đã tải`); $('#last-sync').textContent = `Đồng bộ ${new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}`; renderAll();
        } catch (error) { setConnection('error', 'Kiểm tra URL, route và CORS'); toast(error.message, true); renderAll(); }
        finally { setLoading(false); }
    }

    function renderMetrics() { const values = { scanned: ['scanned', 'total_scanned', 'total_messages'], questions: ['questions', 'valid_questions'], clusters: ['clusters', 'active_clusters'], resolved: ['resolved', 'resolved_clusters'] }; Object.entries(values).forEach(([metric, keys]) => { const node = $(`[data-metric="${metric}"]`); if (node) node.textContent = readMetric(keys); }); $('#queue-nav-count').textContent = state.clusters.filter((item) => item.type !== 'resolved' && item.type !== 'hidden').length || '--'; }
    function renderSignalList() { const target = $('#dashboard-signals'); const items = state.clusters.filter((item) => item.type !== 'resolved' && item.type !== 'hidden').sort((a, b) => b.score - a.score).slice(0, 5); target.innerHTML = items.length ? items.map((item, index) => `<article class="signal-card"><span class="rank">${index + 1}</span><div><div class="card-labels"><span class="pill">${item.count} lượt</span><span class="pill score">Điểm ${item.score || '--'}</span></div><h4>${escapeHtml(item.question || 'Backend chưa trả câu hỏi')}</h4></div><strong class="score-big">${item.score || '--'}</strong></article>`).join('') : emptyState('Chưa có tín hiệu', 'Kết nối backend để hiển thị các cụm câu hỏi thực tế.', 'fa-signal'); }
    function filteredClusters() { const search = $('#search-input').value.trim().toLowerCase(); const type = $('#type-filter').value; const sort = $('#sort-select').value; return state.clusters.filter((item) => (!search || item.question.toLowerCase().includes(search)) && (type === 'all' || item.type === type)).sort((a, b) => sort === 'count' ? b.count - a.count : sort === 'newest' ? String(b.created_at || '').localeCompare(String(a.created_at || '')) : b.score - a.score); }
    function renderQueue() { const target = $('#queue-list'); const items = filteredClusters(); target.innerHTML = items.length ? items.map((item) => `<article class="queue-card"><div class="queue-card-top"><div><div class="card-labels"><span class="pill">${escapeHtml(item.type)}</span><span class="pill">${item.count} lượt</span><span class="pill score">Điểm ${item.score || '--'}</span></div><h3>${escapeHtml(item.question || 'Không có nội dung')}</h3><p class="reason">${escapeHtml(item.reason || 'Backend chưa cung cấp lý do xếp hạng.')}</p></div><span class="rank">#${state.clusters.indexOf(item) + 1}</span></div><div class="queue-actions"><button class="secondary-button detail-action" data-id="${escapeHtml(item.id)}"><i class="fa-solid fa-eye"></i>Xem tin gốc</button>${QARadarApi.getConfig().actionPath ? `<button class="primary-button resolve-action" data-id="${escapeHtml(item.id)}"><i class="fa-solid fa-check"></i>Đã xử lý</button><button class="danger-button hide-action" data-id="${escapeHtml(item.id)}"><i class="fa-solid fa-eye-slash"></i>Ẩn câu hỏi</button>` : ''}</div></article>`).join('') : emptyState(QARadarApi.isConfigured() ? 'Không tìm thấy câu hỏi' : 'Chưa kết nối dữ liệu', QARadarApi.isConfigured() ? 'Thử đổi từ khóa hoặc bộ lọc.' : 'Mở mục Kết nối API và nhập route backend thật.', 'fa-inbox'); }
    function renderHistory() { $('#history-list').innerHTML = state.history.length ? state.history.map((item) => `<article class="history-card"><i class="fa-solid fa-circle-check"></i><div><strong>${escapeHtml(item.question ?? item.main_question ?? item.text ?? 'Sự kiện xử lý')}</strong><small>${escapeHtml(item.action ?? item.status ?? 'Đã cập nhật')} · ${escapeHtml(item.created_at ?? item.updated_at ?? '')}</small></div></article>`).join('') : emptyState('Chưa có lịch sử', 'Lịch sử sẽ xuất hiện khi backend cung cấp history endpoint.', 'fa-clock-rotate-left'); }
    function renderAll() { renderMetrics(); renderSignalList(); renderQueue(); renderHistory(); }

    function showView(view) { state.view = view; $$('.view').forEach((node) => node.classList.toggle('active', node.dataset.page === view)); $$('.nav-item').forEach((node) => node.classList.toggle('active', node.dataset.view === view)); const titles = { dashboard: 'Tổng quan', queue: 'Live queue', history: 'Lịch sử', settings: 'Kết nối API' }; $('#view-title').textContent = titles[view]; if (view === 'settings') fillSettings(); }
    function fillSettings() { const config = QARadarApi.getConfig(); [['base-url', 'baseUrl'], ['stats-path', 'statsPath'], ['clusters-path', 'clustersPath'], ['action-path', 'actionPath'], ['history-path', 'historyPath']].forEach(([id, key]) => { $(`#api-${id}`).value = config[key]; }); }
    function openModal(cluster) { $('#modal-title').textContent = cluster.question || 'Chi tiết cụm'; const messages = Array.isArray(cluster.messages) ? cluster.messages : []; $('#modal-body').innerHTML = messages.length ? messages.map((message) => `<div class="source-message">${escapeHtml(typeof message === 'string' ? message : message.text ?? message.student_question ?? '')}</div>`).join('') : emptyState('Không có tin gốc', 'Backend chưa trả danh sách messages cho cụm này.', 'fa-comment-slash'); $('#detail-modal').classList.add('open'); $('#detail-modal').setAttribute('aria-hidden', 'false'); }
    async function updateCluster(id, status) { try { await QARadarApi.updateCluster(id, { status }); toast('Đã cập nhật trạng thái.'); await loadData(); } catch (error) { toast(error.message, true); } }

    $$('.nav-item').forEach((button) => button.addEventListener('click', () => showView(button.dataset.view))); $$('[data-navigate]').forEach((button) => button.addEventListener('click', () => showView(button.dataset.navigate))); $('#refresh-button').addEventListener('click', loadData); $('#queue-refresh').addEventListener('click', loadData); $('#search-input').addEventListener('input', renderQueue); $('#type-filter').addEventListener('change', renderQueue); $('#sort-select').addEventListener('change', renderQueue); $('#settings-shortcut').addEventListener('click', () => showView('settings')); $('#close-modal').addEventListener('click', () => $('#detail-modal').classList.remove('open')); $('#detail-modal').addEventListener('click', (event) => { if (event.target.id === 'detail-modal') $('#detail-modal').classList.remove('open'); }); $('#dashboard-signals').addEventListener('click', (event) => { const card = event.target.closest('.signal-card'); if (card) showView('queue'); }); $('#queue-list').addEventListener('click', (event) => { const id = event.target.closest('[data-id]')?.dataset.id; if (!id) return; const cluster = state.clusters.find((item) => String(item.id) === String(id)); if (event.target.closest('.detail-action')) openModal(cluster); if (event.target.closest('.resolve-action')) updateCluster(id, 'resolved'); if (event.target.closest('.hide-action')) updateCluster(id, 'hidden'); });
    $('#settings-form').addEventListener('submit', (event) => { event.preventDefault(); QARadarApi.saveConfig({ baseUrl: $('#api-base-url').value, statsPath: $('#api-stats-path').value, clustersPath: $('#api-clusters-path').value, actionPath: $('#api-action-path').value, historyPath: $('#api-history-path').value }); toast('Đã lưu cấu hình API.'); loadData(); }); $('#test-connection').addEventListener('click', async () => { if (!QARadarApi.isConfigured()) return toast('Cần có Base URL và route clusters trước.', true); try { await QARadarApi.getClusters(); setConnection('online', 'Kết nối thành công'); toast('Backend phản hồi thành công.'); } catch (error) { setConnection('error', 'Kết nối thất bại'); toast(error.message, true); } }); $('#start-session-button').addEventListener('click', () => toast('Backend chưa có endpoint bắt đầu phiên.', true));
    document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('#detail-modal').classList.remove('open'); });
    renderAll(); loadData();
})();
